version: "3.8"

services:
  mongodb:
    image: mongo:7.0
    container_name: mesocycle_mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: mesocycle_planner
    volumes:
      - mongodb_data:/data/db
      - ./infrastructure/persistence/seed:/docker-entrypoint-initdb.d
    networks:
      - mesocycle_network

  mongo-express:
    image: mongo-express:latest
    container_name: mesocycle_mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
    networks:
      - mesocycle_network

volumes:
  mongodb_data:
    driver: local

networks:
  mesocycle_network:
    driver: bridge
